# Simplified Nixpacks configuration for backend only
# Use this if the full nixpacks.toml fails

[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd backend && python manage.py migrate",
    "cd backend && python manage.py create_demo_data"
]

[start]
cmd = "cd backend && gunicorn course_organizer.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"