[phases.setup]
nixPkgs = ["python3", "pip", "nodejs", "npm"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd backend && python manage.py migrate",
    "cd backend && python manage.py create_demo_data",
    "cd frontend && npm run build:prod"
]

[start]
cmd = "cd backend && gunicorn course_organizer.wsgi:application --bind 0.0.0.0:$PORT"