# Generated by Django 5.2.6 on 2025-09-11 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_of',
            field=models.IntegerField(blank=True, help_text='Graduation year (Class of) - auto-calculated from student_class', null=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Class name (e.g., 'Class of 2029')", max_length=100)),
                ('program', models.CharField(choices=[('GPR', 'Bachelor of Laws (LLB)'), ('LAW', 'Law Program'), ('ENG', 'Engineering'), ('MED', 'Medicine'), ('SCI', 'Science'), ('BUS', 'Business'), ('ART', 'Arts'), ('EDU', 'Education')], help_text='Academic program', max_length=10)),
                ('graduation_year', models.IntegerField(help_text='Expected graduation year')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year this class started', on_delete=django.db.models.deletion.CASCADE, to='directory.academicyear')),
            ],
            options={
                'ordering': ['-graduation_year', 'program'],
                'unique_together': {('program', 'graduation_year')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='Student class (for students)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='directory.class'),
        ),
    ]
