# Generated by Django 5.2.6 on 2025-09-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_user_class_of_class_user_student_class'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='Student class (for students)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.class'),
        ),
    ]
