# Generated by Django 5.2.6 on 2025-09-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_alter_course_target_classes'),
        ('directory', '0003_alter_user_student_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
