# Generated by Django 5.2.6 on 2025-09-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='first_semester_end',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='first_semester_start',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='second_semester_end',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='second_semester_start',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_type', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')], help_text='Type of semester')),
                ('start_date', models.DateField(help_text='Semester start date')),
                ('end_date', models.DateField(help_text='Semester end date')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active semester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='directory.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'semester_type'],
                'unique_together': {('academic_year', 'semester_type')},
            },
        ),
    ]
