# Generated by Django 5.2.6 on 2025-10-08 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_remove_academicyear_first_semester_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser and device information')),
                ('device_type', models.CharField(blank=True, help_text='Mobile, Desktop, Tablet', max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, help_text='City, Country from IP', max_length=200)),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=255)),
                ('success', models.BooleanField(default=True, help_text='Whether login was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='directory_l_login_t_a6e4ce_idx'), models.Index(fields=['user', '-login_time'], name='directory_l_user_id_fffe6a_idx'), models.Index(fields=['ip_address'], name='directory_l_ip_addr_27170c_idx')],
            },
        ),
    ]
