# Generated by Django 5.2.6 on 2025-09-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recording_enabled',
            field=models.BooleanField(default=True, help_text='Whether recording is enabled for this meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Unique meeting identifier for Jitsi', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='platform',
            field=models.CharField(choices=[('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('physical', 'Physical Meeting'), ('other', 'Other')], default='jitsi', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True, help_text='URL to the recorded meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='course_api.timetableentry'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='JitsiRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(help_text='Jitsi recording ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recording_url', models.URLField(blank=True, help_text='URL to the completed recording')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Recording file size in bytes', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Actual recording duration', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='course_api.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
