# Generated by Django 5.2.6 on 2025-10-30 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
        ('course_content', '0002_alter_announcement_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, help_text='Users mentioned with @', related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='referenced_materials',
            field=models.ManyToManyField(blank=True, help_text='Materials referenced with //', related_name='referenced_in_messages', to='course_content.material'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Topics/hashtags mentioned with #'),
        ),
    ]
