# Generated by Django 5.2.6 on 2025-09-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes this course is designed for', related_name='courses', to='school.class'),
        ),
    ]
