# Generated by Django 5.2.6 on 2025-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='lecturer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
