# Generated by Django 5.2.6 on 2025-09-14 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_alter_meeting_options_meeting_is_recording_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='admin_host',
            field=models.ForeignKey(blank=True, help_text='Admin user who will be the default host', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_auto_created',
            field=models.BooleanField(default=False, help_text='Whether this meeting was auto-created from a timetable entry'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room_password',
            field=models.CharField(blank=True, help_text='Optional password for the meeting room', max_length=50),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='has_video_call',
            field=models.BooleanField(default=False, help_text='Whether this class has an associated video call'),
        ),
    ]
