# Generated by Django 5.2.6 on 2025-10-08 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_add_reply_to_group_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the message was deleted', null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages_deleted', to=settings.AUTH_USER_MODEL),
        ),
    ]
