# Generated by Django 5.2.6 on 2025-10-30 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_add_message_references'),
        ('course_content', '0002_alter_announcement_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='referenced_materials',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='referenced_course_materials',
            field=models.ManyToManyField(blank=True, help_text='Course materials referenced with [[]]', related_name='referenced_in_messages', to='course_content.material'),
        ),
        migrations.CreateModel(
            name='GroupMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='group_materials/')),
                ('file_url', models.URLField(blank=True, help_text='External link to material')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('video', 'Video File'), ('audio', 'Audio File'), ('image', 'Image'), ('link', 'External Link'), ('other', 'Other')], default='other', help_text='Type of material', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course_api.studygroup')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_materials_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Material',
                'verbose_name_plural': 'Group Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='referenced_group_materials',
            field=models.ManyToManyField(blank=True, help_text='Group materials referenced with [[]]', related_name='referenced_in_messages', to='course_api.groupmaterial'),
        ),
    ]
