# Generated by Django 5.2.6 on 2025-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0003_meeting_admin_host_meeting_is_auto_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='daily_room_id',
            field=models.CharField(blank=True, help_text='Daily.co room ID', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='daily_room_name',
            field=models.CharField(blank=True, help_text='Daily.co room name', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='daily_room_url',
            field=models.URLField(blank=True, help_text='Daily.co room URL'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='daily_token',
            field=models.TextField(blank=True, help_text='Daily.co meeting token'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.IntegerField(default=50, help_text='Maximum number of participants'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='platform',
            field=models.CharField(choices=[('daily', 'Daily.co'), ('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('physical', 'Physical Meeting'), ('other', 'Other')], default='daily', max_length=20),
        ),
    ]
