# Generated by Django 5.2.6 on 2025-10-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0003_add_soft_delete_to_group_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='xmpp_room_jid',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='xmpp_room_name',
        ),
    ]
