# Generated by Django 5.2.6 on 2025-09-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0006_studygroup_groupmeeting_studygroupjoinrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeeting',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location if platform is physical', max_length=255),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course focus for the study group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='course_api.course'),
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='platform',
            field=models.CharField(choices=[('jitsi', 'Jitsi Meet'), ('daily', 'Daily.co'), ('physical', 'Physical Meeting')], default='jitsi', max_length=20),
        ),
    ]
