# Generated by Django 5.2.6 on 2025-09-30 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0007_groupmeeting_location_studygroup_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='xmpp_room_jid',
            field=models.CharField(blank=True, help_text='Full room JID for XMPP MUC (e.g., sg-123@conference.example.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='xmpp_room_name',
            field=models.CharField(blank=True, help_text='Local room name for XMPP MUC (e.g., sg-123)', max_length=120),
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='course_api.studygroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
