# Generated by Django 5.2.6 on 2025-09-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.class'),
        ),
        migrations.AlterField(
            model_name='classreprole',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reps', to='school.class'),
        ),
        migrations.AlterField(
            model_name='message',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_messages', to='school.class'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='school.class'),
        ),
    ]
