# Generated by Django 5.2.6 on 2025-09-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file_url',
            field=models.CharField(blank=True, help_text='Direct URL to the content', max_length=500),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_url',
            field=models.CharField(blank=True, help_text='Direct URL to the content', max_length=500),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='file_url',
            field=models.CharField(blank=True, help_text='Direct URL to the content', max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_url',
            field=models.CharField(blank=True, help_text='Direct URL to the content', max_length=500),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='file_url',
            field=models.CharField(blank=True, help_text='Direct URL to the content', max_length=500),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file_url',
            field=models.CharField(blank=True, help_text='Direct URL to the content', max_length=500),
        ),
    ]
